print('hello World')
print('what is your name')
myName = input()
print('its goot to meet you,' + myName)
print('the length of your name is: ')
print(len(myName))
print('what is your age')
age = input()
print('you will be ' + str(int(age) + 1) + ' in a year')